Learn-Schema translation done
GraphQL-China/graphql-china.github.io pull request #27
Opened 2017-07-20 04:03 UTC by jonirrings

Signed-off-by: Jonir Rings <peterpuyi@live.cn>

2017-07-20 09:39 UTC, ydfzgyj requested changes
看了一半，感觉错别字什么的有点太多了……你还是先再自查一遍，然后再 review 吧……

2017-07-20 09:39 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +title: Schema和类型
还是中英文之间空格的问题

2017-07-20 09:39 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +因为一个GraphQL查询的结构几乎匹配其结果，因此即便不知到服务器的情况，你也能预测查询会返回什么结果。但是一个关于我们所需要的数据的确切描述依然很有意义，我们能选择什么字段？服务器会返回哪种对象？这些对象下有那些字段可用？这便是schema的来历。
即便“不知道”服务器的情况

2017-07-20 09:39 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +如果你之前见到过GraphQL查询，你就知道GraphQL查询语言基本上就是关于选择对象上的字段。因此，例如下列查询中：
例如“在”下列查询中

2017-07-20 09:39 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +GraphQL服务可以用任何语言编写，因为我们并不依赖与任何特定语言的句法句式（譬如JavaScript）来与GraphQL schema沟通，我们定义了自己的简单语言，称之为“GraphQL schema语言”——他和GraphQL的查询语言很相似，让我们能够和GraphQL schema之间可以无语言差异地沟通。
1. 并不依赖“于”任何特定语言
2. 让我们`能够`和GraphQL schema之间`可以`无语言差异地沟通，“能够”和“可以”意思重复，应当删掉其中的一个

2017-07-20 09:39 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +GraphQL服务可以用任何语言编写，因为我们并不依赖与任何特定语言的句法句式（譬如JavaScript）来与GraphQL schema沟通，我们定义了自己的简单语言，称之为“GraphQL schema语言”——他和GraphQL的查询语言很相似，让我们能够和GraphQL schema之间可以无语言差异地沟通。
统一用“它”比较好

2017-07-20 09:39 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +一个GraphQL schema的中最基本组件是对象类型，它就表示你可以从服务上获取到什么类型对象，这个对象有什么字段。使用GraphQL schema语言，我们可以这让表示它：
1. schema“中的”最基本组件
2. 它<del>就</del>表示你可以从服务上获取到什么类型“的”对象，“以及”这个对象有什么字段
3. 我们可以“这样”表示它

2017-07-21 01:28 UTC, jonirrings commented on site/learn/Learn-Schema.md
> +GraphQL服务可以用任何语言编写，因为我们并不依赖与任何特定语言的句法句式（譬如JavaScript）来与GraphQL schema沟通，我们定义了自己的简单语言，称之为“GraphQL schema语言”——他和GraphQL的查询语言很相似，让我们能够和GraphQL schema之间可以无语言差异地沟通。
:joy:好多都是typo

2017-07-21 01:29 UTC, jonirrings commented
:joy:哎……typo好多。

2017-07-21 01:58 UTC, jonirrings commented
修了一下typo，麻烦再审一下。

2017-07-21 06:32 UTC, linonetwo reviewed
一些用词值得商榷，后面大部分都蛮好的啦

2017-07-21 06:32 UTC, linonetwo commented on site/learn/Learn-Schema.md
> +如果你之前见到过 GraphQL 查询，你就知道 GraphQL 查询语言基本上就是关于选择对象上的字段。因此，例如在下列查询中：
selecting fields on objects 是 obj.field 的意思，说成「选择」不大习惯，「取出怎么样」

2017-07-21 06:32 UTC, linonetwo commented on site/learn/Learn-Schema.md
> +2. 选择其上的 `hero` 字段
就是一种选择之后还要取过来用的感觉

2017-07-21 06:32 UTC, linonetwo commented on site/learn/Learn-Schema.md
> +因为一个 GraphQL 查询的结构几乎匹配其结果，因此即便不知道服务器的情况，你也能预测查询会返回什么结果。但是一个关于我们所需要的数据的确切描述依然很有意义，我们能选择什么字段？服务器会返回哪种对象？这些对象下有那些字段可用？这便是 schema 的来历。
「几乎匹配」这边可以说成「查询的结构和结果非常相似」，我觉得。还要 comes in 可以翻作 「引入……的理由」

2017-07-21 06:32 UTC, linonetwo commented on site/learn/Learn-Schema.md
> +虽然这语言可读性相当好，但我们还是检阅一下，以便我们可以有些共通的词汇：
检阅一下 是不是可以翻作「一起看看下面的用语」

2017-07-22 09:09 UTC, ydfzgyj requested changes
比上次好多了，还有一些小问题

2017-07-22 09:09 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +- `name` 和 `appearsIn` 是 `Character` 类型上的_字段_。这意味着出现在一个 GraphQL 查询中的字段，唯独 `name` 和 `appearsIn` 可以操作 `Character` 类型。
最后一句整句都感觉不通……应该是断句就断错了

2017-07-22 09:09 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +GraphQL 对象类型上的每一个字段都可能有另个或者多个参数，例如下面的 `length` 字段：
“零个或多个”

2017-07-22 09:09 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +参数可能是必选或者可选的，当一个参数是可选的，我们可以定义一个_默认值_ —— 如果 `unit` 参数没有传递，那么它将会被默认设置 `METER` 为。
1. “可能是”改成“可以是”更好
2. 默认设置为 `METER`

2017-07-22 09:09 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +每一个 GraphQL 服务都有一个 `query` 类型，可能有也可能没有一个 `mutation` 类型。这两个类型和常规对象类型无差，但是它们之所以特殊，是因为它们定义了每一个 GraphQL 查询的_入口_。因此如果你看到一个像这样的查询：
这里不用直译吧，直接“可能有一个 `mutation` 类型”就好了

2017-07-22 09:09 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +变更也是类似的工作方式 —— 你在 `Mutation` 类型上定义一些字段，然后这些字段将在根 mutation 字段可用，接着你就能在你的查询中调用。
“mutation 根字段” 比 “根 mutation 字段” 更好理解一些

2017-07-22 09:09 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +有比记住的是，除了作为 schema 的入口，`Query` 和 `Mutation` 类型与其它 GraphQL 对象类型别无二致，它们字段也是一样的工作方式。
1. 有必要记住的是
2. 它们的字段

2017-07-22 09:09 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +- `Float`：有符号上精度浮点值。
双精度

2017-07-22 09:09 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +- `Int`：有符号32位整数。
32 两边应该加空格

2017-07-22 09:09 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +- `String`：UTF‐8字符序列。
UTF‐8 后边加空格

2017-07-22 09:09 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +- `ID`：ID标量类型表示一个唯一标识符，通常作为键以重新获取缓存中的对象。ID 类型使用和 String 一样的方式序列化；然而将其定义为 ID 意味着并不需要人类可读型。
1. “标量类型”前加空格
2. often used to refetch an object `or` as the key for a cache，应该是一个并列关系

2017-07-22 09:09 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +也称作_枚举/enum _，枚举类型是一种特殊的标量，它限制在一个特殊的可选值集合内。这让你能够：
英文和标点之间不用加空格

2017-07-22 09:09 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +1. 验证任何参数是这个类型可选值的的某一个
应该是“这个类型中的任何参数”吧

2017-07-22 09:09 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +对象类型，标量以及枚举是 GraphQL 中你唯一可以定义的类型种类。但是当你在 schema 的其他部分使用这些类型时，或者在你的查询变量声明处使用时，你可以给它们应用额外的_类型修改器_来影响这些值的验证。我们先来看一个例子：
modifiers 在这里应该翻译成“修饰符”，下同

2017-07-22 09:09 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +非空类型修改器也可以用于定义字段上的参数，如果这个参数上传递了一个空值（不管通过 GraphQL string 还是变量），那么会导致服务器返回一个验证错误。
这里的 string 应该可以翻译的

2017-07-22 09:09 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +联合类型十分接近接口，但是它并不指定类型之间的任何共同字段。
“十分接近”稍有点奇怪，“联合类型和接口十分相似”怎么样？

2017-07-22 09:09 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +输入对象类型上的字段它们自己可以指代输入对象类型，但是你不能在你的 schema 混淆输入和输出类型。输入对象类型的字段当然也不能拥有参数。
输入对象类型上的字段“本身也”可以指代输入对象类型

2017-07-24 02:15 UTC, jonirrings commented on site/learn/Learn-Schema.md
> +如果你之前见到过 GraphQL 查询，你就知道 GraphQL 查询语言基本上就是关于选择对象上的字段。因此，例如在下列查询中：
这个`select`和规范的`selection set`是对应的。我翻译的是 `选择`和`选择集`。`取出`的话和规范那个怎么对应？有木有思路？

2017-07-24 02:16 UTC, jonirrings commented on site/learn/Learn-Schema.md
> +虽然这语言可读性相当好，但我们还是检阅一下，以便我们可以有些共通的词汇：
嗯嗯,go over始终不好翻译。

2017-07-24 02:21 UTC, jonirrings commented on site/learn/Learn-Schema.md
> +因为一个 GraphQL 查询的结构几乎匹配其结果，因此即便不知道服务器的情况，你也能预测查询会返回什么结果。但是一个关于我们所需要的数据的确切描述依然很有意义，我们能选择什么字段？服务器会返回哪种对象？这些对象下有那些字段可用？这便是 schema 的来历。
`That's where the schema comes in`翻译成`这便轮到了 schema 登场`如何？

2017-07-24 02:26 UTC, jonirrings commented on site/learn/Learn-Schema.md
> +- `name` 和 `appearsIn` 是 `Character` 类型上的_字段_。这意味着出现在一个 GraphQL 查询中的字段，唯独 `name` 和 `appearsIn` 可以操作 `Character` 类型。
感觉需要补充一些介词和连词。
已修正了一下，你再检查看看

2017-07-24 02:29 UTC, jonirrings commented on site/learn/Learn-Schema.md
> +变更也是类似的工作方式 —— 你在 `Mutation` 类型上定义一些字段，然后这些字段将在根 mutation 字段可用，接着你就能在你的查询中调用。
调整一下，意译。
然后这些字段将作为 mutation 根字段使用

2017-07-24 02:34 UTC, jonirrings commented on site/learn/Learn-Schema.md
> +对象类型，标量以及枚举是 GraphQL 中你唯一可以定义的类型种类。但是当你在 schema 的其他部分使用这些类型时，或者在你的查询变量声明处使用时，你可以给它们应用额外的_类型修改器_来影响这些值的验证。我们先来看一个例子：
好的，我们项目中有叫作 decorator 的东西。感觉有点纠结这个翻译。先按照你说的翻译

2017-07-24 02:36 UTC, jonirrings commented on site/learn/Learn-Schema.md
> +联合类型十分接近接口，但是它并不指定类型之间的任何共同字段。
嗯嗯，中文的 接近 有动词的意思。英文的 resemble 有动词意思，哈哈哈:joy:。

2017-07-24 02:37 UTC, jonirrings commented on site/learn/Learn-Schema.md
> +输入对象类型上的字段它们自己可以指代输入对象类型，但是你不能在你的 schema 混淆输入和输出类型。输入对象类型的字段当然也不能拥有参数。
对哦，self可以翻译成 本身。

2017-07-24 02:37 UTC, jonirrings commented
感谢大佬的审校。有劳再次检查

2017-07-24 03:46 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +对象类型，标量以及枚举是 GraphQL 中你唯一可以定义的类型种类。但是当你在 schema 的其他部分使用这些类型时，或者在你的查询变量声明处使用时，你可以给它们应用额外的_类型修改器_来影响这些值的验证。我们先来看一个例子：
decorator 应该是装饰器吧

2017-07-24 07:21 UTC, ydfzgyj reviewed
有两个地方之前上次 review 写的不是很详细，这次详细说明了一下我的想法，可以再讨论一下

2017-07-24 07:21 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +因为一个 GraphQL 查询的结构和结果非常相似，因此即便不知道服务器的情况，你也能预测查询会返回什么结果。但是一个关于我们所需要的数据的确切描述依然很有意义，我们能选择什么字段？服务器会返回哪种对象？这些对象下有那些字段可用？这便是引入 schema 的原因。
这些对象下有“哪些”字段可用

2017-07-24 07:21 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +一个 GraphQL schema 的中最基本的组件是对象类型，它就表示你可以从服务上获取到什么类型的对象，以及这个对象有什么字段。使用 GraphQL schema 语言，我们可以这样表示它：
“中的”最基本的组件

2017-07-24 07:21 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +- `name` 和 `appearsIn` 是 `Character` 类型上的_字段_。这意味着在一个 GraphQL 查询里出现的字段当中，唯独 `name` 和 `appearsIn` 是可以操作 `Character` 类型的。
嗯……我觉得这句的断句应该是这样
That means that `name` and `appearsIn` are the only fields that can appear in any part of **（a GraphQL query that operates on the `Character` type）**.
所以这句我觉得应该翻译成：
这意味着在一个操作 `Character` 类型的 GraphQL 查询中的任何部分只能出现 `name` 和 `appearsIn` 字段。

2017-07-24 07:21 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +- `ID`：ID 标量类型表示一个唯一标识符，通常作为键以重新获取缓存中的对象。ID 类型使用和 String 一样的方式序列化；然而将其定义为 ID 意味着并不需要人类可读型。
这里的“通常作为键以重新获取缓存中的对象”没改呀，我还是觉得这里应该是“用来重新获取对象或作为缓存中的键”，因为这里其实一个是缓存一个是清除缓存，还是不太一样

2017-07-24 07:29 UTC, jonirrings commented on site/learn/Learn-Schema.md
> +- `name` 和 `appearsIn` 是 `Character` 类型上的_字段_。这意味着在一个 GraphQL 查询里出现的字段当中，唯独 `name` 和 `appearsIn` 是可以操作 `Character` 类型的。
嗯好，看来是断句的差异。

2017-07-24 07:33 UTC, jonirrings commented on site/learn/Learn-Schema.md
> +- `ID`：ID 标量类型表示一个唯一标识符，通常作为键以重新获取缓存中的对象。ID 类型使用和 String 一样的方式序列化；然而将其定义为 ID 意味着并不需要人类可读型。
:joy:，这个是我的错，真·看岔了。

2017-07-24 07:33 UTC, jonirrings commented
已经修正，有劳再次审核

2017-07-24 07:46 UTC, ydfzgyj approved these changes

2017-07-24 07:46 UTC, merged